### PR TITLE
Security/User processors converted

### PR DESCRIPTION
**Pull request by alroniks**
Task modxcms#14547

To get User/Setting converted in this PR also converted the required System/Setting processors.

### CODE REVIEW

**Comment by opengeek** [comment]
Do not merge the base branch back into your work. Always rebase your outstanding commits on top of updates to the base branch.

**Comment by opengeek** [comment]
@Alroniks is this still in progress? It is still marked as draft…

**Comment by alroniks** [comment]
@opengeek Yes, trying to finish with user validation

**Comment by JoshuaLuckers** [comment]
Also apply the changes from this PR (once merged): https://github.com/modxcms/revolution/pull/14511

**Pull request merged**
